version: '3'

services:
  db:
    build:
      context: .
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_data_buckups:/backups
    environment:
      - POSTGRES_DB=network
      - POSTGRES_USER=network
      - POSTGRES_PASSWORD=LTiSD2t6vRCn4a18
    env_file:
      - ./.envs/.postgres
  django:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: /start

volumes:
  postgres_data: {}
  postgres_data_buckups: {}